name: Build BestGrid EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install --upgrade pip pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --name BestGridApp_v1 BestGridApp_v1.py
          dir dist

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: BestGridApp_Windows_EXE
          path: dist/BestGridApp_v1.exe